<Project Sdk="Microsoft.Net.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)'==''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>SanteDB.Queue.Msmq</PackageId>
		<Title>SanteDB Server MSMQ Persistent Queue</Title>
		<Version>$(VersionNumber)</Version>
		<Description>Allows SanteDB to use Microsoft(r) Message Queues as the persistent query provider</Description>
		<Authors>SanteSuite Contributors</Authors>
		<PackageTags>SanteDB</PackageTags>
		<RepositoryUrl>https://github.com/santedb/santedb-msmq</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeSymbols>true</IncludeSymbols>
		<Product>SanteDB</Product>
		<Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
		<Company>SanteSuite Contributors</Company>
		<PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
		<PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
	</PropertyGroup>
	<Choose>
		<When Condition="$(SolutionName.Contains('-nuget'))">
			<ItemGroup>
				<PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
				<ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
			</ItemGroup>
		</Otherwise>
	</Choose>
	<ItemGroup>
		<None Include="..\..\SanteDB.licenseheader">
			<Link>SanteDB.licenseheader</Link>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="System.Messaging" />
	</ItemGroup>
</Project>